### ISSUE TITLE
New Data Stored in iD but not rendering or in backup

### ISSUE THREAD

**Issue by jonnyhuck** [posm/posm#351]
I ran a mapathon in Uganda using a POSM and (though it had worked well in testing) the data from the actual mapathon did not render onto the map tiles, nor is it in the backup PBF. It is, however, still visible (and saved) in the iD editor. 

I think that this is v0.8.2 (though if there is a way I can verify this it would be much appreciated), and it is the standard POSM build.

As far as I can tell the changesets are in the database:
```
select date_trunc('day',created_at), count(*) from changesets group by date_trunc('day',created_at) order by date_trunc('day',created_at) desc;

     date_trunc      | count 
---------------------+-------
 2019-03-06 00:00:00 |    14
 2019-03-05 00:00:00 |   110
 2019-03-04 00:00:00 |     5
 2019-03-03 00:00:00 |     8
 2019-02-26 00:00:00 |  4078    //this is the import


select date_trunc('day',c.created_at), count(*) from changesets c left join ways w on c.id = w.changeset_id group by date_trunc('day',c.created_at) order by date_trunc('day',c.created_at) desc;

     date_trunc      | count  
---------------------+--------
 2019-03-06 00:00:00 |    166    
 2019-03-05 00:00:00 |   2284    
 2019-03-04 00:00:00 |    266    
 2019-03-03 00:00:00 |    368    
 2019-02-26 00:00:00 | 118855    //this is the import
```

Do you have any hints for how I might be able to diagnose/resolve this?

Thanks very much.

**Comment by mojodna** [comment]
To determine the version of POSM you're using, run:

```bash
cd /root/posm-build
git tag
```

It'll be the highest version number listed there. (Almost certainly 0.8.2 for you, which is great. OSM doesn't work in 0.8.3 and we'll have an 0.9.0 out soon that addresses it.)

The backup PBF is the initial version of the data that was loaded. It would make sense to periodically dump the latest version, but POSM doesn't currently do that.

Instead, you can create a PBF including changes made with POSM using:

```bash
osmosis --read-apidb authFile=/etc/osmosis/osm.properties validateSchemaVersion=no --write-pbf /opt/data/backups/posm-latest.pbf
```

(If you want to pull the data out for post-POSM purposes, this is probably the file you want.)

The rendering database is updated using Osmosis replication files, which are in `/opt/data/osm` (http://posm.io/replication/). `###.osc.gz` files larger than 108 bytes contain changes (`find . -type f -name \*.osc.gz -size +108c` to list just those). Individual OsmChange files can be opened with `gzip -dc 002.osc.gz` to see if they contain the data you expect.

There's a systemd timer (and corresponding service) in `/etc/systemd/system/osm2pgsql-replication.{service,timer}` that pulls them. Have a look at the end of the service's logs to see if `osm2pgsql` is running:

```bash
journalctl -u osm2pgsql-replication.service
```

It should include something like this when it applies changes:

```
Jun 02 18:50:42 posm apply-updates.sh[19182]: Osm2pgsql took 0s overall
```

You can go hunting for features that were added by poking around in the rendering database directly:

```bash
sudo -u postgres psql -d gis
```

```sql
-- get the feature ID using iD
select * from planet_osm_point where osm_id=6516079090;
```

If all the data is there as expected, the problem may lie within the tile server. It keeps cached copies of tiles, so to ensure that it's rendering new data, it needs to be restarted:

```bash
systemctl restart tessera
```

You can then browse tiles through the OSM interface or directly from `http://posm.io/tiles/mm`. To fully eliminate caching as a problem, either clear your browser cache or open the Network Inspector and check the "Disable cache" box:

![image](https://user-images.githubusercontent.com/45/58765986-10e5db80-852e-11e9-9898-72365089ac3a.png)

**Comment by jonnyhuck** [comment]
Thankyou for all of that detail - it is very useful!

It looks like I am actually on *0.8.1*, which seems odd looking at the release dates, but glad I checked! 

It also looks like *osm2pgsql* is having a problem:

```
Jun 03 14:37:19 posm systemd[1]: Starting osm2pgsql replication...
Jun 03 14:37:19 posm apply-updates.sh[3089]: osm2pgsql version 0.94.0 (64 bit id space)
Jun 03 14:37:19 posm apply-updates.sh[3089]: Using built-in tag processing pipeline
Jun 03 14:37:19 posm apply-updates.sh[3089]: Using projection SRS 3857 (Spherical Mercator)
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_point
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_line
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_polygon
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_roads
Jun 03 14:37:19 posm apply-updates.sh[3089]: Allocating memory for dense node cache
Jun 03 14:37:19 posm apply-updates.sh[3089]: Allocating dense node cache in one big chunk
Jun 03 14:37:19 posm apply-updates.sh[3089]: Allocating memory for sparse node cache
Jun 03 14:37:19 posm apply-updates.sh[3089]: Sharing dense sparse
Jun 03 14:37:19 posm apply-updates.sh[3089]: Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=11
Jun 03 14:37:19 posm apply-updates.sh[3089]: Mid: pgsql, cache=800
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_nodes
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_ways
Jun 03 14:37:19 posm apply-updates.sh[3089]: Setting up table: planet_osm_rels
Jun 03 14:37:20 posm apply-updates.sh[3089]: Reading in file: -
Jun 03 14:37:20 posm apply-updates.sh[3089]: Using XML parser.
Jun 03 14:37:20 posm apply-updates.sh[3089]: node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%
Jun 03 14:37:20 posm apply-updates.sh[3089]: Osm2pgsql failed due to ERROR: XML parsing error at line 1, column 0: no element found
Jun 03 14:37:20 posm systemd[1]: osm2pgsql-replication.service: Main process exited, code=exited, status=1/FAILURE
Jun 03 14:37:20 posm systemd[1]: osm2pgsql-replication.service: Failed with result 'exit-code'.
Jun 03 14:37:20 posm systemd[1]: Failed to start osm2pgsql replication.
```

The *.osc files look okay on the face of it, the very last one seems to be 0 size, but I get the same error if I move it (in its gzip) and the corresponding `.state.txt` file elsewhere (and call the script manually):
```
root@posm:~# sudo -u gis /usr/local/bin/apply-updates.sh
osm2pgsql version 0.94.0 (64 bit id space)

Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=11
Mid: pgsql, cache=800
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: -
Using XML parser.
node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%
Osm2pgsql failed due to ERROR: XML parsing error at line 1, column 0: no element found
```

However, If I just run the osmosis part of `apply-updates.sh` manually:
```bash
osmosis \
     --read-replication-interval \
       workingDirectory=/opt/data/osm \
     --simplify-change \
     --write-xml-change 
```
Then I get this:
```
Jun 04, 2019 2:54:33 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.46
Jun 04, 2019 2:54:33 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Jun 04, 2019 2:54:33 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Jun 04, 2019 2:54:33 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Jun 04, 2019 2:54:33 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property.
	at org.openstreetmap.osmosis.replication.common.ReplicationState.loadProperty(ReplicationState.java:65)
	at org.openstreetmap.osmosis.replication.common.ReplicationState.load(ReplicationState.java:78)
	at org.openstreetmap.osmosis.replication.common.ReplicationState.<init>(ReplicationState.java:59)
	at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:103)
	at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:46)
	at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:257)
	at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:350)
	at java.base/java.lang.Thread.run(Thread.java:844)

Jun 04, 2019 2:54:33 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```
which I guess suggests that there is an issue with one of the state.txt files.

`/opt/data/osm/replication/minute/state.txt` is blank (though I think that this is output from the above command, so perhaps this is expected?)

The latest one related to an individual change is also blank as I said above (`/opt/data/osm/replication/minute/000/000/391.state.txt`), the one before it (`/opt/data/osm/replication/minute/000/000/390.state.txt`) is not:

```
cat /opt/data/osm/replication/minute/000/000/390.state.txt 
#Mon Mar 04 03:50:17 UTC 2019
sequenceNumber=390
txnMaxQueried=4215
txnActiveList=
txnReadyList=
txnMax=4215
timestamp=2019-03-04T03\:50\:17Z
```
The majority of our data was collected on Tues 5th and Wed 6th of March, so I guess that this problem likely goes back a bit further down the pipeline. 

Do I therefore need to make new replication files using osmosis, I guess by comparing the `osm` database with the original `.pbf` file? What do you think?

Thanks once again

**Comment by jonnyhuck** [comment]
I have extracted the update .pbf file as you suggested and added to a new database like this:
```
createdb gulu-post
psql gulu-post -c "create extension postgis; create extension hstore;"
psql gulu-post -f /opt/osmosis/script/pgsnapshot_schema_0.6.sql
osmosis --read-pbf post.pbf --write-pgsql database="gulu-post"
```
I have then set up a directory to output all of the change files to (using the original first `state.txt` file that was written to the POSM) 
```
mkdir replication
osmosis —rrii
scp root@posm.io:/opt/data/osm/replication/minute/000/000/000.state.txt ./replication/state.txt
```
I then attempt to make the change files with:
```
osmosis --replicate-apidb database=gulu-post validateSchemaVersion=no --write-replication workingDirectory=./replication/
```
But I get this error:
```
Jun 09, 2019 10:15:04 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.47
Jun 09, 2019 10:15:05 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Jun 09, 2019 10:15:05 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Jun 09, 2019 10:15:05 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Jun 09, 2019 10:15:05 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-replicate-apidb failed
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [CREATE TEMPORARY TABLE tmp_nodes ON COMMIT DROP AS SELECT node_id, version FROM nodes WHERE (((xid_to_int4(xmin) >= ? AND xid_to_int4(xmin) <= ?))) AND redaction_id IS NULL]; nested exception is org.postgresql.util.PSQLException: ERROR: column "node_id" does not exist
  Position: 59
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1414)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:883)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:317)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.EntityDao.getHistory(EntityDao.java:454)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.AllEntityDao.getHistory(AllEntityDao.java:52)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.Replicator.replicateImpl(Replicator.java:385)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.Replicator.access$000(Replicator.java:20)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.Replicator$1.run(Replicator.java:263)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.TransactionDao$1.doInTransactionWithoutResult(TransactionDao.java:61)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.openstreetmap.osmosis.apidb.common.DatabaseContext2.executeWithinTransaction(DatabaseContext2.java:94)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.TransactionDao.executeWithinTransaction(TransactionDao.java:58)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.Replicator.replicateLoop(Replicator.java:260)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.Replicator.replicate(Replicator.java:242)
	at org.openstreetmap.osmosis.apidb.v0_6.ApidbFileReplicator.runImpl(ApidbFileReplicator.java:89)
	at org.openstreetmap.osmosis.apidb.v0_6.ApidbFileReplicator.run(ApidbFileReplicator.java:99)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: column "node_id" does not exist
  Position: 59
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)
	at org.springframework.jdbc.core.JdbcTemplate$$Lambda$4/434926837.doInPreparedStatement(Unknown Source)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 18 more

Jun 09, 2019 10:15:05 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```
The main issue here is  clearly:
```
ERROR: column "node_id" does not exist
```
Though I am not too sure what the cause iof this could be (as I initialised it with the `pgsnapshot_schema_0.6.sql`). Do you have any idea what I need to do here?

Thanks very much.

**Comment by mojodna** [comment]
Fantastic!

Sorry for disappearing last week. Your solution makes total sense (that was the same path I was going to start exploring) and, best of all, it worked!

**Comment by mojodna** [comment]
(Re: an earlier version of your comment, the Osmosis schema in use is `apidb`)

**Comment by jonnyhuck** [comment]
Ah - that's great - thanks very much!
