### ISSUE TITLE
Field Papers Tiling Error: Invalid tilesource protocol: raster+http:

### ISSUE THREAD

**Issue by jonnyhuck** [posm/posm#359]
When I up load an image to Field papers, the tiles are not loading wither in the preview or in iD.  I am using **Build: 0.9.0** and the image was taken with a Google Pixel Smartphone. I (think that I) have narrowed it down to a problem with `fp-tiler`.

Here is the output from `journalctl -xe -u fp-task`:

```
Jan 15 23:02:07 posm npm[1459]: Error: Invalid tilesource protocol: raster+http:
Jan 15 23:02:07 posm npm[1459]:     at Object.tilelive.load (/opt/fp/fp-tiler/node_modules/@mapbox/tilelive/lib/tilelive.js:94:25)
Jan 15 23:02:07 posm npm[1459]:     at Object.tilelive.load (/opt/fp/fp-tiler/node_modules/tilelive-streaming/index.js:533:12)
Jan 15 23:02:07 posm npm[1459]:     at /opt/fp/fp-tiler/node_modules/tilelive-cache/index.js:266:23
Jan 15 23:02:07 posm npm[1459]:     at lock (/opt/fp/fp-tiler/node_modules/locking-cache/index.js:57:16)
Jan 15 23:02:07 posm npm[1459]:     at Object.<anonymous> (/opt/fp/fp-tiler/node_modules/tilelive-cache/index.js:265:12)
Jan 15 23:02:07 posm npm[1459]:     at Object.load (/opt/fp/fp-tiler/node_modules/locking-cache/index.js:84:17)
Jan 15 23:02:07 posm npm[1459]:     at Request.<anonymous> (/opt/fp/fp-tiler/node_modules/tilelive-fieldpapers/index.js:45:23)
Jan 15 23:02:07 posm npm[1459]:     at Request._callback (/opt/fp/fp-tiler/node_modules/holdtime/index.js:29:21)
Jan 15 23:02:07 posm npm[1459]:     at Request.self.callback (/opt/fp/fp-tiler/node_modules/request/request.js:185:22)
Jan 15 23:02:07 posm npm[1459]:     at emitTwo (events.js:126:13)
```
I've had a search through POSM, field papers and tessera issues but with no luck. Do you have an idea what the issue might be?

**Comment by jonnyhuck** [comment]
EDIT: *(if it helps)* I am reasonably confident that I installed **0.9.1**, but I reported **0.9.0** above because that is the result of checking `git tag`:
```
root@posm:~# cd /root/posm-build
root@posm:~/posm-build# git tag
v0.1
v0.2
v0.3
v0.4
v0.5
v0.6.0
v0.6.0-beta.2
v0.6.1
v0.7.0
v0.7.1
v0.7.2
v0.8.0
v0.8.1
v0.8.2
v0.8.3
v0.9.0
```
Additionally, if I check the [releases](https://github.com/posm/posm-build/releases) page it looks like I shouldn't have ben able to creatre an atlas with 0.9.0 - I was able to do this with no problem.

**Comment by danbjoseph** [comment]
thank you for logging your issues! unfortunately i'm not the best to troubleshoot this stuff.
i know it doesn't help you right now, but we are working on a new release soon that will hopefully resolve a few issues.

**Comment by jonnyhuck** [comment]
Okay, thanks. If there is anything I can do to help debug this further just let me know.
