### ISSUE TITLE
Fresh install AOI Active Permission Issue

### ISSUE THREAD

**Issue by 1msmith1** [posm/posm#360]
First Time using posm, which I wish I had found a while ago, and I am in need of some assistance.

When attempting to Activate a AOI (from https://export.hotosm.org/) I am getting a permission denied error. I did chmod -R 777 aoi and chmod -R 777 overpass.osm.pbf on the directory and files but they are overwritten by the script. 

------------------------------------------------------------------------

Feb 06, 2020 5:58:29 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.46
Feb 06, 2020 5:58:29 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Feb 06, 2020 5:58:29 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Feb 06, 2020 5:58:29 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Feb 06, 2020 5:58:29 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-pbf-fast failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read PBF file /opt/data/aoi/testdata/osm/overpass.osm.pbf.
        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:50)
        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:40)
        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader.run(PbfReader.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /opt/data/aoi/testdata/osm/overpass.osm.pbf (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:48)
        ... 3 more

Feb 06, 2020 5:58:29 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by danbjoseph** [comment]
Thanks for reaching out. I'm sorry you ran into this issue. It is not something I've seen before.

What version are you using - Standard POSM [v0.9.1](https://github.com/posm/posm-build/releases/tag/v0.9.1)?

Are you installed on an Intel NUC? What model?

How did you [transfer the POSM bundle file](http://posm.io/posm/preparation/#getting-the-aoi-onto-the-posm) - via direct download or manual transfer?

**Comment by 1msmith1** [comment]
I have a fresh copy of the Standard POSM V0.9.1 installed on an Intel NUC NUC5PPYH. 

I have the WiFi setting Set to Bridge and I am using the Direct Download Method by pasting my url from export.hotosm.org.

**Comment by danbjoseph** [comment]
Is the HOT export one you can share with me? If yes, can you email to daniel.joseph@redcross.org and I will try and test it next week.

**Comment by 1msmith1** [comment]
Dan, I have sent you an email with the export link from HOT. Thank you.

**Comment by danbjoseph** [comment]
i have replicated the issue and hit the same error message (copied from the "Show Logs" modal). 
i will continue to investigate.
```
Feb 20, 2020 4:54:38 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.46

Feb 20, 2020 4:54:39 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.

Feb 20, 2020 4:54:39 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.

Feb 20, 2020 4:54:39 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.

Feb 20, 2020 4:54:39 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-pbf-fast failed
                                              org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unableto read PBF file /opt/data/aoi/Entire_County/osm/overpass.osm.pbf.
                                                                        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:50)
                                        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:40)
        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader.run(PbfReader.java:82)
                                                                                at java.lang.Thread.run(Thread.java:748)
           Caused by: java.io.FileNotFoundException: /opt/data/aoi/Entire_County/osm/overpass.osm.pbf (Permission denied)
                at java.io.FileInputStream.open0(Native Method)
                                                                at java.io.FileInputStream.open(FileInputStream.java:195)
                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                                                                                at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:48)
                                                ... 3 more


Feb 20, 2020 4:54:39 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
                          org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
                                                                                                            at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
                                                                                                at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
                                                        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                        at java.lang.reflect.Method.invoke(Method.java:498)
                                                                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
                                                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
                                                        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
                                        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)


false
```

**Comment by danbjoseph** [comment]
fresh install of 0.9.1
`systemctl status` 
![IMG_20200219_165211](https://user-images.githubusercontent.com/4806884/74879983-535b7c80-5338-11ea-8098-25d0c5ef71d8.jpg)
`systemctl list-units`
 ![IMG_20200219_165231](https://user-images.githubusercontent.com/4806884/74880010-61a99880-5338-11ea-8b71-1b403a5f110b.jpg)

**Comment by danbjoseph** [comment]
osm.posm.io returns a `ERR_CONNECTION_CLOSED`
http://posm.io/fp/compose shows the global basemap tiles
![Screen Shot 2020-02-19 at 5 03 29 PM](https://user-images.githubusercontent.com/4806884/74880765-ed6ff480-5339-11ea-97eb-93b3e00e05fb.png)

**Comment by danbjoseph** [comment]
@mojodna with a fresh install of v0.9.1, osm.posm.io isn't resolving and activating an AOI isn't working. i'm using a NUC5PPYH. any chance you might be able to suggest something?

**Comment by mojodna** [comment]
Hey, sorry for the delay (and future delays).

This sounds network-related, probably something around `/etc/hosts` getting reset or something. I thought I'd addressed this (and certainly checked whether it worked). It could also be related to which network interfaces are attached. Sorry I can't be of more help.

**Comment by danbjoseph** [comment]
with install of `posm-auth-replay-tool-2020-April-17-2nd.iso` on an Intel NUC5PPYH also runs into this error
```
May 06, 2020 3:32:44 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-pbf-fast failed
                                              org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read PBF file /opt/data/aoi/DC_test_of_posm-replay/osm/overpass.osm.pbf.
                                                                        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:50)
                                at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:40)
                                                                                                                at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader.run(PbfReader.java:82)
                                                                at java.lang.Thread.run(Thread.java:748)
                                                                                                        Caused by: java.io.FileNotFoundException: /opt/data/aoi/DC_test_of_posm-replay/osm/overpass.osm.pbf (Permission denied)
                                                                                                        at java.io.FileInputStream.open0(Native Method)
                                at java.io.FileInputStream.open(FileInputStream.java:195)
                                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                                        at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader$1.get(PbfReader.java:48)
                                                                                                                       ... 3 more


May 06, 2020 3:32:44 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
                          org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
                                                                                                                at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
                                                                                        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
                                at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
                                                                                                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                                                                       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
                                                                                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
                                                                        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
                                                at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)


false
```
