### ISSUE TITLE
AOI activation failure  (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#366]
when tying to activate a `*-bundle.tar.gz` file get the following log
```
/opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find minitest-5.10.2 in any of the sources (Bundler::GemNotFound)
        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
                                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
                                                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
                                                                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
                                                                                        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
                                from /opt/rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                                from /opt/rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

false
```

**Comment by danbjoseph** [comment]
tried with a fresh install of POSM and the same issue
```
CREATE EXTENSION

CREATE FUNCTION

CREATE FUNCTION

CREATE FUNCTION

==> api-db-drop-create.sh: END


==> /opt/admin/posm-admin/scripts/osm_api-db-init.sh: Initializing API DB with rake db:migrate.


/opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find minitest-5.10.2 in any of the sources (Bundler::GemNotFound)
        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
                                                                                                                        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
                                                                                                                        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
                                                                                                                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
                                                                                                                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
                                                                                                                        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'

        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
        from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
                                                                                                                from /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
                                                                                                                from /opt/rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                                                                                                from /opt/rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

false
```
